
server:
  port: 0
  
spring:
  application:
    name: consumer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    
feign:
  hystrix:
    enabled: true

product:
  iva: 0.16
  desc: impuesto de valor agregado
  defaultMethod: "defaultCircuitBreaker"
  
kafka:
  topic:
    name: my-topic-test
  server:
    host: localhost
    port: 9092
  batch:
    size: 16384
  retires: 0
  linger: 1
